### ISSUE TITLE
ids parameter is not working anymore

### ISSUE THREAD

**Issue by kaggl** [acdh-oeaw/mmp#104]
https://mmp.acdh-dev.oeaw.ac.at/api/usecase/?ids=2,3 should return usecase 2 and 3,
https://mmp.acdh-dev.oeaw.ac.at/api/keyword/?ids=10,20 should return keyword 10 and 20 etc.

these parameters have also been removed from the api-docs

**Comment by csae8092** [comment]
looks like this error is related to the latest django-filter version (22.1)
