### ISSUE TITLE
Issues with text start & end date

### ISSUE THREAD

**Issue by kaggl** [acdh-oeaw/mmp#113]
I've run into some issues using text__start_date and text__end_date attributes:
1. when texts have a starting date but no end date, the api shouldnt return texts that start after the given end date
example: https://mmp.acdh-dev.oeaw.ac.at/api/stelle/?format=json&text__start_date=400&text__start_date_lookup=gt&text__end_date=760&text__end_date_lookup=lt
this should only return passages from texts between the years 400 and 760, but since the text has no end date, the first result is a passage from a text written in 825

**Comment by kaggl** [comment]
2. while mostly working as expected, there is an occasional passsage with a text thats outside of the given range,
example: https://mmp.acdh-dev.oeaw.ac.at/api/stelle/?format=json&limit=10&offset=30&has_usecase=true&text__start_date=680&text__start_date_lookup=gt&text__end_date=960&text__end_date_lookup=lt
the first two passages returned have texts outside the given years 680 - 960

**Comment by csae8092** [comment]
there was a bug in the filter querying the wrong data fields. This was fixed. I close this issue for now, @kaggl please reopen the issue and provide some sample queries in case you notice some further erratic behavior related to start/enddate filters
