### ISSUE TITLE
provide custom layer config for case studies (use cases)

### ISSUE THREAD

**Issue by stefanprobst** [acdh-oeaw/mmp#150]
use cases currently have a `custom_layer` field which accepts a single magic string (e.g. "800") which will be resolved by the client to a hardcoded list of geojson feature collections.

change this to a new `GeojsonLayer` class (many-to-many) which has:
- id
- title
- attribution (optional)
- the actual geojson data
- description (optional)

**Comment by csae8092** [comment]
add some mgm-cmd to populate this new class
