### ISSUE TITLE
add text and passage start and end dates to keyword-data

### ISSUE THREAD

**Issue by kaggl** [acdh-oeaw/mmp#153]
The rvn_stelle_key_word_keyword__text__autor__start_date_year and rvn_stelle_key_word_keyword__text__not_before keys don't seem to do anything when used with the keyword-data endpoint

**Comment by csae8092** [comment]
please provide the full links (and ideally a count of the returned nodes)

**Comment by kaggl** [comment]
👌
[https://mmp.acdh-dev.oeaw.ac.at/archiv/keyword-data/
?rvn_stelle_key_word_keyword__text__autor=46](https://mmp.acdh-dev.oeaw.ac.at/archiv/keyword-data/?rvn_stelle_key_word_keyword__text__autor=46)
46 nodes

[https://mmp.acdh-dev.oeaw.ac.at/archiv/keyword-data/
?rvn_stelle_key_word_keyword__text__autor=46
&rvn_stelle_key_word_keyword__text__not_before=400
&rvn_stelle_key_word_keyword__text__not_after=410](https://mmp.acdh-dev.oeaw.ac.at/archiv/keyword-data/?rvn_stelle_key_word_keyword__text__autor=46&rvn_stelle_key_word_keyword__text__not_before=400&rvn_stelle_key_word_keyword__text__not_after=410)
this too has 46 nodes.

It doesn't matter which dates are used here, these results are always the same.

[https://mmp.acdh-dev.oeaw.ac.at/archiv/keyword-data/
?rvn_stelle_key_word_keyword__text__autor=46
&rvn_stelle_key_word_keyword__start_date=400
&rvn_stelle_key_word_keyword__start_date_lookup=gt
&rvn_stelle_key_word_keyword__end_date=410
&rvn_stelle_key_word_keyword__end_date_lookup=lt](https://mmp.acdh-dev.oeaw.ac.at/archiv/keyword-data/?rvn_stelle_key_word_keyword__text__autor=46&rvn_stelle_key_word_keyword__start_date=400&rvn_stelle_key_word_keyword__start_date_lookup=gt&rvn_stelle_key_word_keyword__end_date=410&rvn_stelle_key_word_keyword__end_date_lookup=lt)
this has 47 nodes for some reason, when changing the dates there can be even more nodes:
[https://mmp.acdh-dev.oeaw.ac.at/archiv/keyword-data/
?rvn_stelle_key_word_keyword__text__autor=46
&rvn_stelle_key_word_keyword__start_date=900
&rvn_stelle_key_word_keyword__start_date_lookup=gt
&rvn_stelle_key_word_keyword__end_date=910
&rvn_stelle_key_word_keyword__end_date_lookup=lt](https://mmp.acdh-dev.oeaw.ac.at/archiv/keyword-data/?rvn_stelle_key_word_keyword__text__autor=46&rvn_stelle_key_word_keyword__start_date=900&rvn_stelle_key_word_keyword__start_date_lookup=gt&rvn_stelle_key_word_keyword__end_date=910&rvn_stelle_key_word_keyword__end_date_lookup=lt)
has 128

**Comment by csae8092** [comment]
as of https://github.com/acdh-oeaw/mmp/pull/155 
* keyword-data endpoint is now called keyword-network and queries Stelle/Passages -> accepts query-params from `/api/stelle` endpoint
* ideally this means that this issue has become obsolet; but needs some proper testing

**Comment by csae8092** [comment]
no further complains, so this issue is finally closed
