### ISSUE TITLE
add proper pagination for generic autocomplete

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/mmp#162]
in relation to #152

**Comment by stefanprobst** [comment]
apart from pagination query params, we would also have to clarify the sorting behavior - e.g. if i request the first page of results, the default page size is 25, and my search term matches 20 keywords and 20 authors. would results be sorted by entity type (so i would get back 20 authors + 5 keywords), or alphabetically by entity label, or by some other ranking mechanism?
