### ISSUE TITLE
handle additional `type` field in generic autocomplete

### ISSUE THREAD

**Issue by stefanprobst** [acdh-oeaw/mmp#164]
one open issue from https://github.com/acdh-oeaw/mmp/issues/152 was how to handle keyword subtypes in a generic autocomplete endpoint. i.e. currently we have separate endpoints for author/keyword/place/passage/text/usecase models, but additional endpoints for every keyword type (name, region, ethnonym, keywordkeyword).

while i think being able to query by subtype (i.e. allowing an additional `?type=` query param) is nice to have, it's not strictly necessary.

however what *would* be good to have was a way to include the `art` field in the autocomplete responses. maybe this could be added to the config object?

```py
GENERIC_AC_CONFIG = [
    {
        "app_name": 'archiv',
        "model_name": 'keyword',
        "search_fields": [
            'stichwort',
        ],
        "meta_field": "art"
    }
]
```

**Comment by csae8092** [comment]
ok, next try: in the ac-config add something like
```python
"additional_fields": {
            "art": {
                "lookup": "art",
                "label": "Type of Keyword"
            }
        },
```
