### ISSUE TITLE
include passage places in spatial coverage response (to be displayed as related places)

### ISSUE THREAD

**Issue by stefanprobst** [acdh-oeaw/mmp#180]
currently, the `/spatialcoverage` endpoint includes info about related texts on the geojson properties object, but only very basic info on the related passage.

this may be relevant to the option to display "related places" on the frontend geo-map view, which currently uses `feature.properties.texts[].places[]` to display "related places" - however these are already represented as "cone origins", i.e. "places of composition".

instead of `texts.places,` "related places" on the frontend should therefore probably refer to `stelle.places` instead, i.e. "places mentioned in the passage".

pending decision from the researchers, this would probably mean including info on `stelle.places` [here](https://github.com/acdh-oeaw/mmp/blob/master/archiv/models.py#L1668-L1677).

**Comment by csae8092** [comment]
currently there are ~ 33 passages with related places; so I guess `Stelle.ort` will be deleted (hopefully) soon anyways

**Comment by stefanprobst** [comment]
afaiu the decision is that passage.places will be removed, so this issue can be closed.
