### ISSUE TITLE
[feature] api endpoint for compare-keywords-by-author graph

### ISSUE THREAD

**Issue by stefanprobst** [acdh-oeaw/mmp#183]
recently, the frontend has added a new kind of network graph to compare keyword use by author. example: https://acdh-oeaw.github.io/mmp-frontend/#/explore/compare?Author=9%2B7

currently, this requires four requests by the client to compare keywords by two authors: one requests for each author (needed to get the author name which should be displayed as the author node label), and two separate requests to `/archiv/keyword-network?text__autor=:id` to get keywords used by a specific author. and then the client needs to merge these two graphs (i.e. figure out which nodes are shared by the graphs).

it would be great to have a dedicated api endpoint for this.

the returned graph object should include, in addition to what the current `/api/keyword-network` endpoint returns:
- an author node for each of the requested authors
- edges between keyword nodes and author nodes for each keyword used by an author

**Comment by csae8092** [comment]
https://github.com/acdh-oeaw/mmp/commit/2c54dad119cc7e2582b83cebb664860c98fb9aa3
