### ISSUE TITLE
keyword graph: include edge count instead of serializing multiple edges with same source and target nodes

### ISSUE THREAD

**Issue by stefanprobst** [acdh-oeaw/mmp#188]
currently, we cap the size of a returned keyword graph at 500 nodes - see [here](https://github.com/acdh-oeaw/mmp/blob/master/archiv/endpoint_views.py#L125-L128) and [here](https://github.com/acdh-oeaw/mmp/blob/master/archiv/endpoint_views.py#L150-L153).

the reason for this is to avoid sending huge payloads for big graphs - e.g. an empty query to `/archiv/keyword-network` will return a 4.5 MB payload. most of this is because we currently serialize every edge, even when source and target nodes are the same.

we could avoid this by including a `count` field on edges.

example:

instead of:

```json
{
  "nodes": [{ "id": "node1" }, { "id": "node2" }],
  "edges": [
    { "source": "node1", "target": "node2" },
    { "source": "node1", "target": "node2" },
  ]
}
```

we would return:

```json
{
  "nodes": [{ "id": "node1" }, { "id": "node2" }],
  "edges": [
    { "source": "node1", "target": "node2", "count": 2 },
  ]
}
```

**Comment by stefanprobst** [comment]
also note that, afaiu, we don't care about edge direction, so `{ "source": "node1", "target": "node2" }` and `{ "source": "node2", "target": "node1" }` would be treated as equivalent.

**Comment by csae8092** [comment]
example response for (new) graph-data suggested by @stefanprobst 
```json
{
    "nodes": [
        {
            "key": "keyword__1",
            "id": 1,
            "kind": "keyword",
            "type": "Ethnonym",
            "label": "Angli"
        },
        {
            "key": "autor__1",
            "id": 1,
            "kind": "autor",
            "label": "Stefan"
        }
    ],
    "edges": [
        {
            "key": "autor__1__keyword__1",
            "source": "autor__1",
            "target": "keyword__1"
        }
    ]
}
```
