### ISSUE TITLE
add "status" field to case study model

### ISSUE THREAD

**Issue by stefanprobst** [acdh-oeaw/mmp#191]
it should be possible to set a `status` field for a case study, with allowed values "draft" and "published".

all case studies should always be visible and editable in the django interface, but for API consumers, case studies should *not* be visible as long as `status: "draft"`.

**Comment by csae8092** [comment]
@stefanprobst  can I make it a boolean-field called "published" with True (meaning published) and False (meaning draft)

**Comment by stefanprobst** [comment]
totally :+1:
