### ISSUE TITLE
add text__autor filters to keyword-author-network endpoint

### ISSUE THREAD

**Issue by kaggl** [acdh-oeaw/mmp#195]
using author keys in keyword-author-network only adds author nodes and edges to the already existing keyword-network. The desired response would omit all nodes that are not connected to any author nodes. this is possible by adding text__autor keys for each author to the request, but should be the default.

**Comment by csae8092** [comment]
since this seems to be a very easy fix frontend-side (passing two more params) I won't spend time on this issue
