### ISSUE TITLE
keyword-author-network returns edges to non existing nodes when using has_usecase filter

### ISSUE THREAD

**Issue by kaggl** [acdh-oeaw/mmp#196]
This occured when using the has_usecase filter:

https://mmp.acdh-dev.oeaw.ac.at/archiv/keyword-author-network/author=1&text__autor=1&author=17&text__autor=17&author=5&text__autor=5

this is working just fine, but when I add `has_usecase=true`

https://mmp.acdh-dev.oeaw.ac.at/archiv/keyword-author-network/?has_usecase=true&author=1&text__autor=1&author=17&text__autor=17&author=5&text__autor=5

at least one node (keyword_1, 'abbas') is ommited, which is expected, but the edge connecting the author to this node is still present, throwing an error 

![image](https://user-images.githubusercontent.com/48437174/213201716-9b337fcd-3bec-4873-97f9-f345ab4ae973.png)

**Comment by kaggl** [comment]
this also happens when using other parameters, the author nodes have edges that are independent to the actual result, and dont get filtered automatically.

This is a very good example: 
https://mmp.acdh-dev.oeaw.ac.at/archiv/keyword-author-network/?author=1&text__autor_and=1&author=8&text__autor_and=8

**Comment by kaggl** [comment]
Still getting the same errors when using other queries:
https://mmp.acdh-dev.oeaw.ac.at/archiv/keyword-author-network/?has_usecase=true&author=1&text__autor=1&author=17&text__autor=17&author=5&text__autor=5
![image](https://user-images.githubusercontent.com/48437174/214836825-22b44f9a-51fe-4b96-bf01-22ef6a146550.png)

this always occurs when the query contains author id 5 (anonymous- other)

**Comment by csae8092** [comment]
fixed by https://github.com/acdh-oeaw/mmp/commit/7d0d09d9e6c69625316c041766776d1bb93ccd52
