### ISSUE TITLE
places should be sorted alphabetically

### ISSUE THREAD

**Issue by stefanprobst** [acdh-oeaw/mmp#212]
response from `/api/ort` should be sorted alphacetically (by `name`) by default

**Comment by stefanprobst** [comment]
ok, sorry, i think i misunderstood - no api responses are sorted by default correct?

**Comment by csae8092** [comment]
what ever is correct ;)
anyways, the default order is configured in `models.py` like here https://github.com/acdh-oeaw/mmp/blob/master/archiv/models.py#L113

also there is https://github.com/acdh-oeaw/mmp/blob/master/archiv/api_views.py#L81 so ordering should be defined via api-calls

**Comment by stefanprobst** [comment]
is it possible to sort on nested fields? e.g. `text__start_date` for passages?

**Comment by csae8092** [comment]
it for sure is (somehow), but than what to do with text without dates? also this sounds like yet another request nobody thought properly through (and therefore also might not be really needed)

**Comment by stefanprobst** [comment]
well, we should sort passages search results somehow, and it would make sense to sort by either "temporal coverage" or "date of composition", depending on which date filter is active on the date range slider.

how to handle empty dates is https://github.com/acdh-oeaw/mmp/issues/199
